/*
 * 	    compress.cpp              (C) 2006-2008, Aurélien Croc (AP²C)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the
 *  Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 *  $Id$
 * 
 */
#include "compress.h"
#include <cmath>
#include <cstring>
#include <vector>
#include <memory>
#include <array>
#include <span>
#include <cstdint>
#include <algorithm>
#include "page.h"
#include "band.h"
#include "errlog.h"
#include "request.h"
#include "bandplane.h"
#include "printer.h"

#include "algo0x0d.h"
#include "algo0x0e.h"
#include "algo0x11.h"
#include "algo0x13.h"
#include "algo0x15.h"


/*
 * Use bandwidth alignment algorithm for non-list and custom page sizes.
 * This is more or less exactly how is it implemented in the ULD driver.
 *
 * 100 is a hardcoded margin value (50 * 2), as in the driver.
 */
unsigned long _getBandWidthAlignment(unsigned long bandwidth_align,
                                     unsigned long xresolution,
                                     unsigned long inputwidth) {

    const int hardMarginX = 100;
    int divider = 1;
    if (xresolution == 600) divider = 2;
    if (xresolution == 1200) divider = 4;

    inputwidth = (inputwidth / divider - hardMarginX) * divider;
    int bw_aligned = (inputwidth + bandwidth_align - 1) / bandwidth_align * bandwidth_align / 8;

    return bw_aligned;
}

/*
 * Look up bandwidths in bytes generated by Samsung ULD for 2020 series
 * Samsung M2026 does not work unless it receives _exactly_ the right bandwidths
 * Use the table lookup for the paper sizes hard-coded inside ULD driver,
 * fallback to generic bandwidth alignment code.
 */
unsigned long _get2020BandWidthInB(unsigned char papertype,
                                   unsigned long xresolution,
                                   unsigned long inputwidth) {
    struct Bw {
        unsigned char papertype;
        unsigned long width[2];  //standard and high resolution
    };

    const Bw bw[] = {
        {0,640,1248},	//letter
        {1,640,1248},	//legal
        {2,608,1216},	//a4
        {3,544,1056},	//executive
        {4,800,1600},	//ledger
        {5,864,1728},	//A3
        {6,288,576},	//Env10
        {7,288,544},	//monarch envelope
        {8,480,928},	//c5 envelope
        {9,320,608},	//DL envelope
        {10,736,1472},	//b4
        {11,544,1056},	//b5
        {12,512,992},	//b5 iso envelope
        {14,288,576},	//postcard 4x6
        {16,416,832},	//a5
        {17,288,576},	//a6
        {18,384,736},	//b6
        {23,320,640},	//c6
        {24,640,1248},	//folio
        {25,256,512},	//EnvPersonal
        {26,288,544},	//Env9
        {27,224,416},	//IndexCard
        {28,640,1248},	//Oficio
        {30,416,800},	//Statement
        {34,800,1568},	//8K
        {35,576,1120}	//16K
    };

    for (unsigned int i=0; i<sizeof(bw)/sizeof(bw[0]); i++) {
        if (bw[i].papertype == papertype) {
            if (xresolution == 600) return bw[i].width[0];
            if (xresolution == 1200) return bw[i].width[1];
            break;
        }
    }

    /*
     * If printing on an unusual PageSize not from the list, use bandwidth
     * alignment algorithm.
     */
    unsigned long bw_aligned = _getBandWidthAlignment(256, xresolution, inputwidth);

    if (bw_aligned >= 32)
        return bw_aligned;

    return 0;
}

static bool _isEmptyBand(std::span<const uint8_t> band)
{
    // Use std::all_of for clarity; modern compilers often vectorize this
    return std::all_of(band.begin(), band.end(), [](uint8_t b) { return b == 0; });
}

static SP::Result<> _compressBandedPage(const Request& request, Page* page)
{
    uint32_t index=0, pageHeight, pageWidth, lineWidthInB, bandHeight;
    uint32_t bandWidth, bandWidthInB, bandSize;
    uint32_t hardMarginX, hardMarginXInB, hardMarginY;
    const uint8_t *planes[4];
    uint32_t bandNumber=0;
    uint8_t colors;

    if (!request.printer()) {
        return SP::Unexpected(SP::Error::InvalidArgument);
    }

    colors = page->colorsNr();
    hardMarginX = (static_cast<uint32_t>(std::ceil(page->convertToXResolution(request.
        printer()->hardMarginX()))) + 7) & ~7;
    hardMarginY = static_cast<uint32_t>(std::ceil(page->convertToYResolution(request.printer()->
        hardMarginY())));
    hardMarginXInB = hardMarginX / 8;
    pageWidth = page->width();
    pageHeight = page->height(); 
    
    if (pageHeight <= hardMarginY) {
         ERRORMSG(_("Page height (%u) is smaller than hard margin (%u)"), pageHeight, hardMarginY);
         return SP::Unexpected(SP::Error::InvalidArgument);
    }
    pageHeight -= hardMarginY;

    page->setWidth(pageWidth);
    page->setHeight(pageHeight);
    lineWidthInB = (pageWidth + 7) / 8;
    bandHeight = static_cast<uint32_t>(request.printer()->bandHeight());
    if (page->xResolution() == 300 && page->yResolution() == 300)
        bandHeight /= 2;

    if (!bandHeight) {
        ERRORMSG(_("Invalid zero band height"));
        return SP::Unexpected(SP::Error::InvalidArgument);
    }

    //Patch for Samsung M2026
    if (request.printer()->specialBandWidth()) {
        bandWidthInB = static_cast<uint32_t>(_get2020BandWidthInB(request.printer()->paperType(),
                                            page->xResolution(),
                                            pageWidth));
        if (!bandWidthInB) bandWidthInB = lineWidthInB;
    } else if (request.printer()->fixedBandWidth()) {
        //Some of QPDL 1 and 2 models require full-width data
        //regardless of the paper size.
        //4960px (620 bytes) for 600 DPI
        bandWidthInB = page->xResolution() * 4960 / 600 / 8;
    }
    else bandWidthInB = lineWidthInB;  //original assumption before M2026 patch
    bandWidth = bandWidthInB * 8;
    
    // Safety check for bandSize
    if (static_cast<uint64_t>(bandWidthInB) * bandHeight > 0x20000000) { // 512MB limit
        ERRORMSG(_("Calculated band size is too large"));
        return SP::Unexpected(SP::Error::MemoryError);
    }
    bandSize = bandWidthInB * bandHeight;

    index = hardMarginY * lineWidthInB;
    
    std::vector<uint8_t> band;
    try {
        band.resize(bandSize);
    } catch (const std::bad_alloc&) {
        return SP::Unexpected(SP::Error::MemoryError);
    }

    for (uint32_t i=0; i < colors; i++) {
        planes[i] = page->planeBuffer(static_cast<uint8_t>(i));
        if (!planes[i]) {
            ERRORMSG(_("Plane %u has no data"), i);
            return SP::Unexpected(SP::Error::LogicError);
        }
    }

    while (pageHeight) {
        uint32_t localHeight = bandHeight;
        std::unique_ptr<Band> current = nullptr;
        bool theEnd = false;

        // Special things to do for the last band
        if (pageHeight < bandHeight) {
            theEnd = true;
            localHeight = pageHeight;
            std::fill(band.begin(), band.end(), 0);
        }

        for (uint32_t i=0; i < colors; i++) {
            std::unique_ptr<Algorithm> algo = nullptr;
            SP::Result<std::unique_ptr<BandPlane>> planeRes = SP::Unexpected(SP::Error::None);

            switch (page->compression()) {
                case 0x0D:
                    algo = std::make_unique<Algo0x0D>();
                    break;
                case 0x0E:
                    algo = std::make_unique<Algo0x0E>();
                    break;
                case 0x11:
                    algo = std::make_unique<Algo0x11>();
                    break;
                default:
                    ERRORMSG(_("Unknown compression algorithm. Aborted"));
                    return SP::Unexpected(SP::Error::InvalidArgument);
            }

            // Copy the data into the band depending on the algorithm options
            if (algo->reverseLineColumn()) {
                // Special case where columns and lines are swapped (transposed)
                for (uint32_t y = 0; y < localHeight; y++) {
                    const uint32_t srcRowStart = index + hardMarginXInB + y * lineWidthInB;
                    const size_t copyWidth = std::min(static_cast<size_t>(lineWidthInB - hardMarginXInB), 
                                                   static_cast<size_t>(bandWidthInB));
                    
                    for (uint32_t x = 0; x < copyWidth; x++) {
                        band[x * bandHeight + y] = planes[i][srcRowStart + x];
                    }
                    // Filling remaining with 0 if necessary
                    for (uint32_t x = static_cast<uint32_t>(copyWidth); x < bandWidthInB; x++) {
                        band[x * bandHeight + y] = 0;
                    }
                }
            } else {
                // Standard row-wise copy
                for (uint32_t y = 0; y < localHeight; y++) {
                    const uint32_t dstRowStart = y * bandWidthInB;
                    const uint32_t srcRowStart = index + hardMarginXInB + y * lineWidthInB;
                    const size_t copyWidth = std::min(static_cast<size_t>(lineWidthInB - hardMarginXInB), 
                                                   static_cast<size_t>(bandWidthInB));

                    std::ranges::copy(std::span(planes[i] + srcRowStart, copyWidth), band.begin() + dstRowStart);
                    if (bandWidthInB > copyWidth) {
                        std::ranges::fill(std::span(band.data() + dstRowStart + copyWidth, bandWidthInB - copyWidth), 0);
                    }
                }
            }

            // Is the band empty?
            if (_isEmptyBand(band)) {
                continue;
            }

            // Check if bytes have to be reversed
            if (algo->inverseByte())
                for (uint32_t j=0; j < bandSize; j++)
                    band[j] = ~band[j];

            // Call the compression method
            planeRes = algo->compress(request, band, bandWidth, bandHeight);
            /*
             * If algorithm 0x0D did not create a plane, it means that the 
             * complementary algorithm 0x0E needs to be used
             */
            if (!planeRes && page->compression() == 0x0D) {
                algo = std::make_unique<Algo0x0E>();
                /* Bytes must be reversed first, as algo0x0D didn't do that. */
                for (uint32_t j = 0; j < bandSize; j++)
                    band[j] = ~band[j];
                /* Do the encoding with algo0x0E. */
                planeRes = algo->compress(request, band, bandWidth, bandHeight);
            }

            if (planeRes) {
                std::unique_ptr<BandPlane> plane = std::move(*planeRes);
                plane->setColorNr(static_cast<uint8_t>(i + 1));
                if (!current)
                    current = std::make_unique<Band>(bandNumber, bandWidth, bandHeight);
                current->registerPlane(std::move(plane));
            } else if (planeRes.error() != SP::Error::None) {
                 return SP::Unexpected(planeRes.error());
            }
        }
        if (current)
            page->registerBand(std::move(current));
        bandNumber++;
        index += lineWidthInB * bandHeight;
        pageHeight = theEnd ? 0 : pageHeight - bandHeight;
    }
    page->flushPlanes();

    return {};
}

#ifndef DISABLE_JBIG
static SP::Result<> _compressBandedJBIGPage(const Request& request, Page* page)
{
    uint32_t index=0, pageHeight, lineWidthInB, bandHeight = 128;
    uint32_t bufferWidth, specialBufferWidthInB, bandSize, hardMarginXInB=13, hardMarginY=100;
    const uint8_t *planes[4];
    std::vector<uint8_t> band[4];
    uint32_t bandNumber=0, xLimitInB, bufferWidthInB;
    auto algo = std::make_unique<Algo0x15>();

    if (!request.printer()) {
        return SP::Unexpected(SP::Error::InvalidArgument);
    }

    /* Image trimming are done from hardware margins defined in the ppd. */
    hardMarginXInB = (static_cast<uint32_t>(std::ceil(page->convertToXResolution(request.
        printer()->hardMarginX()))) + 7) / 8;
    hardMarginY = static_cast<uint32_t>(std::ceil(page->convertToYResolution(request.printer()->
        hardMarginY())));
    
    if (page->height() <= hardMarginY) {
         ERRORMSG(_("Page height (%u) is smaller than hard margin (%u)"), page->height(), hardMarginY);
         return SP::Unexpected(SP::Error::InvalidArgument);
    }
    pageHeight = page->height() - hardMarginY; 
    
    lineWidthInB = ((page->width()) + 7) / 8;
    // Compute the buffer width that is nearest multiple of 256 to the original. 
    bufferWidth = page->width() & ~255;
    if ((bufferWidth + 128) < page->width())
      bufferWidth += 256;
    bandHeight = static_cast<uint32_t>(request.printer()->bandHeight());

    if (request.printer()->specialBandWidth()) {
        specialBufferWidthInB = static_cast<uint32_t>(_get2020BandWidthInB(request.printer()->paperType(),
                                                page->xResolution(),
                                                page->width()));
        if (specialBufferWidthInB) bufferWidth = specialBufferWidthInB * 8;
    }
    // Update the page height.
    page->setHeight(pageHeight);
    // Update the page width.
    page->setWidth(bufferWidth);
    bufferWidthInB = (bufferWidth + 7) / 8;
    
    // Safety check for bandSize
    if (static_cast<uint64_t>(bufferWidthInB) * bandHeight > 0x20000000) {
        ERRORMSG(_("Calculated jbig band size is too large"));
        return SP::Unexpected(SP::Error::MemoryError);
    }
    bandSize = bufferWidthInB * bandHeight;
    index = hardMarginY * lineWidthInB;

    try {
        for (uint32_t i=0; i < page->colorsNr(); i++) {
            band[i].resize(bandSize);
            planes[i] = page->planeBuffer(static_cast<uint8_t>(i));
            if (!planes[i]) {
                ERRORMSG(_("JBIG Plane %u has no data"), i);
                return SP::Unexpected(SP::Error::LogicError);
            }
        }
    } catch (const std::bad_alloc&) {
        return SP::Unexpected(SP::Error::MemoryError);
    }

    /*
       Here, limit the width of the copied image to the buffer, as the buffer
       width varies and can lead to 6 practical cases, the following is a
       condensed code.
    */
    if (hardMarginXInB + bufferWidthInB < lineWidthInB - hardMarginXInB)
        xLimitInB = hardMarginXInB + bufferWidthInB;
    else
        xLimitInB = lineWidthInB - hardMarginXInB;
    bool theEnd = false;
    uint32_t indexSizeIncrement = bandHeight * lineWidthInB;
    uint32_t localHeight = bandHeight;
    while (pageHeight) {
        std::unique_ptr<Band> current = nullptr;
        bool cmyPlanesHasData = false;
        // Special things to do for the last band
        if (pageHeight < bandHeight) {
            theEnd = true;
            localHeight = pageHeight;
            for (uint32_t i=0; i < page->colorsNr(); i++)
                std::fill(band[i].begin(), band[i].end(), 0);
        }
        for (uint32_t i=0; i < page->colorsNr(); i++) {
            for (uint32_t y=0; y < localHeight; y++) {
                const uint32_t dstRowStart = y * bufferWidthInB;
                const uint32_t srcRowStart = index + y * lineWidthInB;
                const size_t copyWidth = xLimitInB - hardMarginXInB;

                // Copy the actual pixel data
                std::ranges::copy(std::span(planes[i] + srcRowStart + hardMarginXInB, copyWidth), 
                                  band[i].begin() + dstRowStart);
                
                // Clear the rest of the buffer row
                if (bufferWidthInB > copyWidth) {
                    std::ranges::fill(std::span(band[i].data() + dstRowStart + copyWidth, 
                                                bufferWidthInB - copyWidth), 0);
                }
            }
        }
        // Are the CMY planes completely empty in the band?
        for (uint32_t i=0; i < static_cast<uint32_t>(page->colorsNr() - 1); i++)
            if (!_isEmptyBand(band[i])) { 
                cmyPlanesHasData = true;
                break;
            };
        // Compress the entire band.
        if (cmyPlanesHasData) {
            for (uint32_t i=0; i < page->colorsNr(); i++) {
                auto planeRes = algo->compress(request, band[i],
                                                  bufferWidth, bandHeight);
                if (planeRes) {
                    std::unique_ptr<BandPlane> plane = std::move(*planeRes);
                    plane->setColorNr(static_cast<uint8_t>((1 == page->colorsNr()) ? 4 : i + 1));
                    if (!current)
                        current = std::make_unique<Band>(bandNumber, bufferWidth, bandHeight);
                    current->registerPlane(std::move(plane));
                } else if (planeRes.error() != SP::Error::None) {
                     return SP::Unexpected(planeRes.error());
                }
            }
        } else if (!_isEmptyBand(band[page->colorsNr() - 1])) { 
            // Compress only the K band.
            auto planeRes = algo->compress(request,
                                              band[page->colorsNr() - 1],
                                              bufferWidth, bandHeight);
            if (planeRes) {
                std::unique_ptr<BandPlane> plane = std::move(*planeRes);
                plane->setColorNr(4);
                if (!current)
                    current = std::make_unique<Band>(bandNumber, bufferWidth, bandHeight);
                current->registerPlane(std::move(plane));
            } else if (planeRes.error() != SP::Error::None) {
                 return SP::Unexpected(planeRes.error());
            }
        }
        if (current)
            page->registerBand(std::move(current));
        bandNumber++;
        index += indexSizeIncrement;
        pageHeight = theEnd ? 0 : pageHeight - bandHeight;
    }
    if (page->bandsNr() > 0)
        page->setBIH(algo->getBIHdata());
    page->flushPlanes();

    return {};
}

static SP::Result<> _compressWholePage(const Request& request, Page* page)
{
    uint32_t hardMarginX, hardMarginXInB, hardMarginY, lineWidthInB;
    uint32_t pageWidth, bandHeight, planeHeight, pageHeight, index;
    uint32_t bandNumber=0;
    std::vector<uint8_t> buffer;
    Band *raw_current = nullptr;
    Algo0x13 algo[4];

    if (!request.printer()) {
        return SP::Unexpected(SP::Error::InvalidArgument);
    }

    hardMarginX = (static_cast<uint32_t>(std::ceil(page->convertToXResolution(request.
        printer()->hardMarginX()))) + 7) & ~7;
    hardMarginY = static_cast<uint32_t>(std::ceil(page->convertToYResolution(request.printer()->
        hardMarginY())));
    hardMarginXInB = hardMarginX / 8;
    
    if (page->width() <= hardMarginX * 2 || page->height() <= hardMarginY * 2) {
        ERRORMSG(_("Page dimensions too small for margins"));
        return SP::Unexpected(SP::Error::InvalidArgument);
    }

    pageWidth = page->width() - hardMarginX * 2;
    pageHeight = page->height() - hardMarginY * 2;
    page->setWidth(pageWidth);
    page->setHeight(pageHeight);
    lineWidthInB = (pageWidth + 7) / 8;
    bandHeight = static_cast<uint32_t>(request.printer()->bandHeight());
    if (!bandHeight) {
        ERRORMSG(_("Invalid zero band height"));
        return SP::Unexpected(SP::Error::InvalidArgument);
    }

    // Alignment of the page height on band height
    planeHeight = ((pageHeight + bandHeight - 1) / bandHeight) * bandHeight;
    
    try {
        buffer.resize(lineWidthInB * planeHeight);
    } catch (const std::bad_alloc&) {
        return SP::Unexpected(SP::Error::MemoryError);
    }

    do {
        std::unique_ptr<Band> current = nullptr;
        for (uint32_t i=0; i < page->colorsNr(); i++) {
            const uint8_t *curPlane = page->planeBuffer(static_cast<uint8_t>(i));
            if (!curPlane) {
                 ERRORMSG(_("Plane %u has no data"), i);
                 return SP::Unexpected(SP::Error::LogicError);
            }
            SP::Result<std::unique_ptr<BandPlane>> planeRes = SP::Unexpected(SP::Error::None);

            index = hardMarginY * (lineWidthInB + 2 * hardMarginXInB) + 
                hardMarginXInB;
            for (uint32_t y = 0; y < pageHeight; y++) {
                const uint32_t dstRowStart = y * lineWidthInB;
                const uint32_t srcRowStart = index + y * (lineWidthInB + 2 * hardMarginXInB);
                
                std::ranges::copy(std::span(curPlane + srcRowStart, lineWidthInB), 
                                  buffer.begin() + dstRowStart);
            }
            std::fill(buffer.begin() + pageHeight * lineWidthInB, buffer.end(), 0);

            // Call the compression method
            planeRes = algo[i].compress(request, buffer, page->width(), 
                planeHeight);
            if (planeRes) {
                std::unique_ptr<BandPlane> plane = std::move(*planeRes);
                plane->setColorNr(static_cast<uint8_t>(i + 1));
                if (!current)
                    current = std::make_unique<Band>(bandNumber, page->width(), 
                        request.printer()->bandHeight());
                current->registerPlane(std::move(plane));
            } else if (planeRes.error() != SP::Error::None) {
                 return SP::Unexpected(planeRes.error());
            }
        }
        raw_current = current.get();
        if (current)
            page->registerBand(std::move(current));
        bandNumber++;
    } while (raw_current);

    page->flushPlanes();

    return {};
}
#endif /* DISABLE_JBIG */

SP::Result<> compressPage(const Request& request, Page* page)
{
    if (!page)
        return SP::Unexpected(SP::Error::InvalidArgument);

    switch(page->compression()) {
        case 0x0D:
        case 0x0E:
        case 0x11:
            return _compressBandedPage(request, page);
        case 0x13:
#ifndef DISABLE_JBIG
            return _compressWholePage(request, page);
#else
            ERRORMSG(_("J-BIG compression algorithm has been disabled during "
                "the compilation. Please recompile SpliX and enable the "
                "J-BIG compression algorithm."));
            return SP::Unexpected(SP::Error::InvalidArgument);
#endif /* DISABLE_JBIG */
        case 0x15:
#ifndef DISABLE_JBIG
            return _compressBandedJBIGPage(request, page);
#else
            ERRORMSG(_("J-BIG compression algorithm has been disabled during "
                "the compilation. Please recompile SpliX and enable the "
                "J-BIG compression algorithm."));
            return SP::Unexpected(SP::Error::InvalidArgument);
#endif /* DISABLE_JBIG */
        default:
            ERRORMSG(_("Compression algorithm 0x%X does not exist"), 
                static_cast<unsigned int>(page->compression()));
            return SP::Unexpected(SP::Error::InvalidArgument);
    }
}

/* vim: set expandtab tabstop=4 shiftwidth=4 smarttab tw=80 cin enc=utf8: */

